// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(2), // digraph
			nil,      // {
			nil,      // }
			nil,      // id
			nil,      // ->
			nil,      // [
			nil,      // ]
			nil,      // empty
			nil,      // ,
			nil,      // =
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // digraph
			nil,          // {
			nil,          // }
			nil,          // id
			nil,          // ->
			nil,          // [
			nil,          // ]
			nil,          // empty
			nil,          // ,
			nil,          // =
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			shift(3), // {
			nil,      // }
			nil,      // id
			nil,      // ->
			nil,      // [
			nil,      // ]
			nil,      // empty
			nil,      // ,
			nil,      // =
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			nil,      // {
			nil,      // }
			shift(7), // id
			nil,      // ->
			nil,      // [
			nil,      // ]
			nil,      // empty
			nil,      // ,
			nil,      // =
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			nil,      // {
			shift(8), // }
			shift(7), // id
			nil,      // ->
			nil,      // [
			nil,      // ]
			nil,      // empty
			nil,      // ,
			nil,      // =
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			reduce(2), // }, reduce: Statements
			reduce(2), // id, reduce: Statements
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			reduce(4), // }, reduce: Statement
			reduce(4), // id, reduce: Statement
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			nil,       // }
			nil,       // id
			shift(10), // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Grammar
			nil,       // digraph
			nil,       // {
			nil,       // }
			nil,       // id
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			reduce(3), // }, reduce: Statements
			reduce(3), // id, reduce: Statements
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			nil,       // }
			shift(11), // id
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			reduce(7), // }, reduce: OptionalAttributes
			reduce(7), // id, reduce: OptionalAttributes
			nil,       // ->
			shift(13), // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			reduce(5), // }, reduce: EdgeStmt
			reduce(5), // id, reduce: EdgeStmt
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			nil,       // }
			shift(14), // id
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			nil,       // }
			nil,       // id
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			shift(17), // =
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			nil,       // }
			nil,       // id
			nil,       // ->
			nil,       // [
			shift(18), // ]
			nil,       // empty
			shift(19), // ,
			nil,       // =
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			nil,       // }
			nil,       // id
			nil,       // ->
			nil,       // [
			reduce(8), // ], reduce: Attributes
			nil,       // empty
			reduce(8), // ,, reduce: Attributes
			nil,       // =
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			nil,       // }
			shift(20), // id
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			reduce(6), // }, reduce: OptionalAttributes
			reduce(6), // id, reduce: OptionalAttributes
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			nil,       // }
			shift(14), // id
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // digraph
			nil,        // {
			nil,        // }
			nil,        // id
			nil,        // ->
			nil,        // [
			reduce(10), // ], reduce: Attribute
			nil,        // empty
			reduce(10), // ,, reduce: Attribute
			nil,        // =
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // {
			nil,       // }
			nil,       // id
			nil,       // ->
			nil,       // [
			reduce(9), // ], reduce: Attributes
			nil,       // empty
			reduce(9), // ,, reduce: Attributes
			nil,       // =
		},
	},
}
