// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 8

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Grammar
		4,  // Statements
		5,  // Statement
		6,  // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Grammar
		-1, // Statements
		9,  // Statement
		6,  // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		12, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		15, // Attributes
		16, // Attribute
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		21, // Attribute
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
}
