// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(2), // digraph
			nil,      // id
			nil,      // {
			nil,      // }
			nil,      // ->
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // digraph
			nil,          // id
			nil,          // {
			nil,          // }
			nil,          // ->
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			shift(3), // id
			nil,      // {
			nil,      // }
			nil,      // ->
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			nil,      // id
			shift(4), // {
			nil,      // }
			nil,      // ->
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			shift(5), // id
			nil,      // {
			nil,      // }
			nil,      // ->
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			nil,      // id
			nil,      // {
			nil,      // }
			shift(9), // ->
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			shift(5),  // id
			nil,       // {
			shift(10), // }
			nil,       // ->
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(2), // id, reduce: Statements
			nil,       // {
			reduce(2), // }, reduce: Statements
			nil,       // ->
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(4), // id, reduce: Statement
			nil,       // {
			reduce(4), // }, reduce: Statement
			nil,       // ->
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			shift(12), // id
			nil,       // {
			nil,       // }
			nil,       // ->
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Grammar
			nil,       // digraph
			nil,       // id
			nil,       // {
			nil,       // }
			nil,       // ->
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(3), // id, reduce: Statements
			nil,       // {
			reduce(3), // }, reduce: Statements
			nil,       // ->
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(5), // id, reduce: EdgeStmt
			nil,       // {
			reduce(5), // }, reduce: EdgeStmt
			nil,       // ->
		},
	},
}
