// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Grammar
		4,  // Statements
		5,  // Statement
		6,  // EdgeStmt
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Grammar
		-1, // Statements
		9,  // Statement
		6,  // EdgeStmt
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
	},
}
