// Code generated by gocc; DO NOT EDIT.

package parser

import . "github.com/awalterschulze/parsing-in-go-example/example03_edges/ast"

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String:     `S' : Grammar	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Grammar : "digraph" id "{" Statements "}"	<< SetGraphName(X[3], X[1]) >>`,
		Id:         "Grammar",
		NTType:     1,
		Index:      1,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return SetGraphName(X[3], X[1])
		},
	},
	ProdTabEntry{
		String:     `Statements : Statement	<< NewGraph(X[0]) >>`,
		Id:         "Statements",
		NTType:     2,
		Index:      2,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return NewGraph(X[0])
		},
	},
	ProdTabEntry{
		String:     `Statements : Statements Statement	<< AppendStmt(X[0].(*Graph), X[1]) >>`,
		Id:         "Statements",
		NTType:     2,
		Index:      3,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return AppendStmt(X[0].(*Graph), X[1])
		},
	},
	ProdTabEntry{
		String:     `Statement : EdgeStmt	<<  >>`,
		Id:         "Statement",
		NTType:     3,
		Index:      4,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `EdgeStmt : id "->" id	<< &Edge{Src: ID(X[0]), Dst: ID(X[2])}, nil >>`,
		Id:         "EdgeStmt",
		NTType:     4,
		Index:      5,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &Edge{Src: ID(X[0]), Dst: ID(X[2])}, nil
		},
	},
}
