// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(2), // digraph
			nil,      // id
			nil,      // {
			nil,      // }
			nil,      // ->
			nil,      // [
			nil,      // ]
			nil,      // empty
			nil,      // ,
			nil,      // =
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // digraph
			nil,          // id
			nil,          // {
			nil,          // }
			nil,          // ->
			nil,          // [
			nil,          // ]
			nil,          // empty
			nil,          // ,
			nil,          // =
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			shift(3), // id
			nil,      // {
			nil,      // }
			nil,      // ->
			nil,      // [
			nil,      // ]
			nil,      // empty
			nil,      // ,
			nil,      // =
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			nil,      // id
			shift(4), // {
			nil,      // }
			nil,      // ->
			nil,      // [
			nil,      // ]
			nil,      // empty
			nil,      // ,
			nil,      // =
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // digraph
			shift(5), // id
			nil,      // {
			nil,      // }
			nil,      // ->
			nil,      // [
			nil,      // ]
			nil,      // empty
			nil,      // ,
			nil,      // =
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // digraph
			reduce(11), // id, reduce: OptionalAttributes
			nil,        // {
			reduce(11), // }, reduce: OptionalAttributes
			shift(12),  // ->
			shift(14),  // [
			nil,        // ]
			nil,        // empty
			nil,        // ,
			shift(15),  // =
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			shift(5),  // id
			nil,       // {
			shift(16), // }
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(2), // id, reduce: Statements
			nil,       // {
			reduce(2), // }, reduce: Statements
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(4), // id, reduce: Statement
			nil,       // {
			reduce(4), // }, reduce: Statement
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(5), // id, reduce: Statement
			nil,       // {
			reduce(5), // }, reduce: Statement
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(6), // id, reduce: Statement
			nil,       // {
			reduce(6), // }, reduce: Statement
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(9), // id, reduce: AttrStmt
			nil,       // {
			reduce(9), // }, reduce: AttrStmt
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			shift(18), // id
			nil,       // {
			nil,       // }
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(8), // id, reduce: NodeStmt
			nil,       // {
			reduce(8), // }, reduce: NodeStmt
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			shift(19), // id
			nil,       // {
			nil,       // }
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			shift(22), // id
			nil,       // {
			nil,       // }
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Grammar
			nil,       // digraph
			nil,       // id
			nil,       // {
			nil,       // }
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(3), // id, reduce: Statements
			nil,       // {
			reduce(3), // }, reduce: Statements
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // digraph
			reduce(11), // id, reduce: OptionalAttributes
			nil,        // {
			reduce(11), // }, reduce: OptionalAttributes
			nil,        // ->
			shift(14),  // [
			nil,        // ]
			nil,        // empty
			nil,        // ,
			nil,        // =
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // id
			nil,       // {
			nil,       // }
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			shift(24), // =
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // digraph
			nil,        // id
			nil,        // {
			nil,        // }
			nil,        // ->
			nil,        // [
			reduce(12), // ], reduce: Attributes
			nil,        // empty
			reduce(12), // ,, reduce: Attributes
			nil,        // =
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			nil,       // id
			nil,       // {
			nil,       // }
			nil,       // ->
			nil,       // [
			shift(25), // ]
			nil,       // empty
			shift(26), // ,
			nil,       // =
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // digraph
			reduce(14), // id, reduce: Attribute
			nil,        // {
			reduce(14), // }, reduce: Attribute
			nil,        // ->
			nil,        // [
			nil,        // ]
			nil,        // empty
			nil,        // ,
			nil,        // =
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			reduce(7), // id, reduce: EdgeStmt
			nil,       // {
			reduce(7), // }, reduce: EdgeStmt
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			shift(27), // id
			nil,       // {
			nil,       // }
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // digraph
			reduce(10), // id, reduce: OptionalAttributes
			nil,        // {
			reduce(10), // }, reduce: OptionalAttributes
			nil,        // ->
			nil,        // [
			nil,        // ]
			nil,        // empty
			nil,        // ,
			nil,        // =
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // digraph
			shift(19), // id
			nil,       // {
			nil,       // }
			nil,       // ->
			nil,       // [
			nil,       // ]
			nil,       // empty
			nil,       // ,
			nil,       // =
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // digraph
			nil,        // id
			nil,        // {
			nil,        // }
			nil,        // ->
			nil,        // [
			reduce(14), // ], reduce: Attribute
			nil,        // empty
			reduce(14), // ,, reduce: Attribute
			nil,        // =
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // digraph
			nil,        // id
			nil,        // {
			nil,        // }
			nil,        // ->
			nil,        // [
			reduce(13), // ], reduce: Attributes
			nil,        // empty
			reduce(13), // ,, reduce: Attributes
			nil,        // =
		},
	},
}
