// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 10

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Grammar
		6,  // Statements
		7,  // Statement
		8,  // EdgeStmt
		9,  // NodeStmt
		10, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		11, // Attribute
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		13, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Grammar
		-1, // Statements
		17, // Statement
		8,  // EdgeStmt
		9,  // NodeStmt
		10, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		11, // Attribute
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		21, // Attributes
		20, // Attribute
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		23, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		28, // Attribute
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Grammar
		-1, // Statements
		-1, // Statement
		-1, // EdgeStmt
		-1, // NodeStmt
		-1, // AttrStmt
		-1, // OptionalAttributes
		-1, // Attributes
		-1, // Attribute
	},
}
