name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src/github.com/awalterschulze/parsing-in-go-example

    steps:
    - name: Set GOPATH
      run: |
        echo "GOPATH=$(dirname $GITHUB_WORKSPACE)/parsing-in-go-example" >> $GITHUB_ENV
        echo "$(dirname $GITHUB_WORKSPACE)/parsing-in-go-example/bin" >> $GITHUB_PATH
      shell: bash

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: src/github.com/awalterschulze/parsing-in-go-example

    - name: dependencies
      run: make dependencies
      working-directory: ${{env.working-directory}}

    - name: regenerate
      run: make regenerate
      working-directory: ${{env.working-directory}}

    - name: build
      run: make build
      working-directory: ${{env.working-directory}}

    - name: check
      run: make check
      working-directory: ${{env.working-directory}}

    - name: test
      run: make test
      working-directory: ${{env.working-directory}}